format = "$time$all"

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%H:%M"
style = "green"

[username]
show_always = true
format = "[$user]($style)@"
style_user = "green"

[hostname]
ssh_only = false
format = "[$hostname]($style):"
style = "yellow"

[directory]
style = "blue"

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[cmd_duration]
style = "yellow"